blog/urls.py
from django.urls import path

from . import views

app_name = 'blog'
urlpatterns = [
    path('', views.index),
    path('create/', views.create, name='create')

]

bookmarks/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('account/', include('account.urls')),
    path('images/', include('images.urls', namespace='images')),
    path('blog/', include('blog.urls', namespace='blog'))

]

if settings.DEBUG:
       urlpatterns += static(settings.MEDIA_URL,
                             document_root=settings.MEDIA_ROOT)

blog/models.py
# Create your models here.

blog/forms.py
from django import forms
from django.contrib.auth.models import User


class TesteForm(forms.Form):
    convidados = forms.ModelMultipleChoiceField(queryset=User.objects.all(),
                                                widget=forms.SelectMultiple(
                                                    attrs={
                                                        'class': 'form-control js-example-basic-multiple',
                                                        'multiple': 'multiple',
                                                        'style': 'width: 100%'}
                                                )
                                                )

blog/views.py
from django.http import JsonResponse
from django.shortcuts import render
from django.template.loader import render_to_string

from .forms import TesteForm


# Create your views here.

def index(request):
    return render(request, 'base_blog.html')


def create(request):
    data = dict()
    form = TesteForm()
    context = {
        'form': form
    }

    data['html_form'] = render_to_string('blog/blog.html', context=context,
                                         request=request)

    return JsonResponse(data)

blog/templates/base_blog.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
    <!-- Bootstrap CSS -->
    <link rel="stylesheet"
          href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css"
          integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm"
          crossorigin="anonymous">
    {#    <link href="https://cdn.jsdelivr.net/npm/select2@4.1.0-rc.0/dist/css/select2.min.css"#}
    {#          rel="stylesheet"/>#}
    <link rel="stylesheet"
          href="https://cdn.jsdelivr.net/npm/bootstrap-select@1.13.14/dist/css/bootstrap-select.min.css">
</head>
<body>
<div class="container">
    <!-- Button trigger modal -->
    <button type="button" class="js-create-book btn btn-primary"
            data-url="{% url 'blog:create' %}">
        Launch demo modal
    </button>
    <select class="selectpicker" multiple data-live-search="true">
        <option>Mustard</option>
        <option>Ketchup</option>
        <option>Relish</option>
    </select>


    <!-- Modal -->
    <div class="modal fade" id="modal" tabindex="-1" role="dialog"
         aria-labelledby="exampleModalLabel" aria-hidden="true">
        <div class="modal-dialog" role="document">
            <div class="modal-content">

            </div>
        </div>
    </div>

</div>

<script src="https://cdn.jsdelivr.net/npm/jquery@3.6.0/dist/jquery.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js"
        integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q"
        crossorigin="anonymous"></script>
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js"
        integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl"
        crossorigin="anonymous"></script>
{#<script src="https://cdn.jsdelivr.net/npm/select2@4.1.0-rc.0/dist/js/select2.min.js"></script>#}
<script src="https://cdn.jsdelivr.net/npm/bootstrap-select@1.13.14/dist/js/bootstrap-select.min.js"></script>

<script>
    $(document).ready(function () {
        $('select').selectpicker();
        $('.js-example-basic-multiple').select2();

        $(".js-create-book").click(function () {
            var btn = $(this);  // <-- HERE
            $.ajax({
                url: btn.attr("data-url"),  // <-- AND HERE
                type: 'get',
                dataType: 'json',
                beforeSend: function () {
                    $("#modal").modal("show");
                },
                success: function (data) {
                    $("#modal .modal-content").html(data.html_form);
                }
            });
        });

    });
</script>
</body>
</html>