account/urls.py
from django.contrib.auth import views as auth_views
from django.urls import path

from . import views

urlpatterns = [
    path('turma/', views.CreateTurma.as_view(), name='turma-create'),
    path('form/', views.create_book_normal),
    # post views
    path('home/', views.create_book, name='index'),
    path('create_book/', views.BookCreateView.as_view(), name='create_book'),
    path('books/', views.book_list, name='book_list'),
    path('books/create/', views.book_create, name='book_create'),
    path('books/<int:pk>/update/', views.book_update, name='book_update'),
    path('update/<int:pk>', views.BookUpdateView.as_view(), name='update_book'),
    path('register/', views.register, name='register'),
    path('edit/', views.edit, name='edit'),
    # path('login/', views.user_login, name='login'),
    path('login/', auth_views.LoginView.as_view(), name='login'),
    path('logout/', auth_views.LogoutView.as_view(), name='logout'),
    path('password_change/',
         auth_views.PasswordChangeView.as_view(),
         name='password_change'),
    path('password_change/done/',
         auth_views.PasswordChangeDoneView.as_view(),
         name='password_change_done'),
    path('', views.dashboard, name='dashboard'),
    # reset password urls
    path('password_reset/',
         auth_views.PasswordResetView.as_view(),
         name='password_reset'),
    path('password_reset/done/',
         auth_views.PasswordResetDoneView.as_view(),
         name='password_reset_done'),
    path('reset/<uidb64>/<token>/',
         auth_views.PasswordResetConfirmView.as_view(),
         name='password_reset_confirm'),
    path('reset/done/',
         auth_views.PasswordResetCompleteView.as_view(),
         name='password_reset_complete'),
    path('users/', views.user_list, name='user_list'),
    path('users/follow/', views.user_follow, name='user_follow'),
    path('users/<username>/', views.user_detail, name='user_detail'),

]

blog/urls.py
from django.urls import path

from . import views

app_name = 'blog'
urlpatterns = [
    path('', views.index),
    path('create/', views.create, name='create')

]

bookmarks/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('account/', include('account.urls')),
    path('images/', include('images.urls', namespace='images')),
    path('blog/', include('blog.urls', namespace='blog'))

]

if settings.DEBUG:
       urlpatterns += static(settings.MEDIA_URL,
                             document_root=settings.MEDIA_ROOT)

images/urls.py
from django.urls import path
from . import views

app_name = 'images'
urlpatterns = [
    path('create/', views.image_create, name='create'),
    path('detail/<int:id>/<slug:slug>/',
         views.image_detail, name='detail'),
    path('like/', views.image_like, name='like'),
    path('', views.image_list, name='list'),

]

account/models.py
from django.conf import settings
from django.contrib.auth import get_user_model
from django.db import models


class Turma(models.Model):
    professores = models.ManyToManyField(settings.AUTH_USER_MODEL)


class Profile(models.Model):
    user = models.OneToOneField(settings.AUTH_USER_MODEL,
                                on_delete=models.CASCADE)
    date_of_birth = models.DateField(blank=True, null=True)
    photo = models.ImageField(upload_to='users/%Y/%m/%d/',
                              blank=True)

    def __str__(self):
        return f'Profile for user {self.user.username}'


class Book(models.Model):
    HARDCOVER = 1
    PAPERBACK = 2
    EBOOK = 3
    BOOK_TYPES = (
        (HARDCOVER, 'Hardcover'),
        (PAPERBACK, 'Paperback'),
        (EBOOK, 'E-book'),
    )
    title = models.CharField(max_length=50)
    description = models.TextField()
    publication_date = models.DateField(null=True)
    author = models.CharField(max_length=30, blank=True)
    price = models.DecimalField(max_digits=5, decimal_places=2)
    pages = models.IntegerField(blank=True, null=True)
    book_type = models.PositiveSmallIntegerField(choices=BOOK_TYPES)


class Contact(models.Model):
    user_from = models.ForeignKey('auth.User',
                                  related_name='rel_from_set',
                                  on_delete=models.CASCADE)
    user_to = models.ForeignKey('auth.User', related_name='rel_to_set',
                                on_delete=models.CASCADE)
    created = models.DateTimeField(auto_now_add=True, db_index=True)

    class Meta:
        ordering = ('-created',)

    def __str__(self):
        return f'{self.user_from} follows {self.user_to}'


# Add following field to User dynamically
user_model = get_user_model()
user_model.add_to_class('following',
                        models.ManyToManyField('self', through=Contact,
                                               related_name='followers',
                                               symmetrical=False))

account/forms.py
from bootstrap_modal_forms.forms import BSModalModelForm
from django import forms
from django.contrib.auth.models import User
from django.forms import formset_factory

from .models import Profile, Book, Turma


class TurmaForm(forms.ModelForm):
    turma = forms.ModelMultipleChoiceField(queryset=User.objects.all(),
                                           widget=forms.SelectMultiple(
                                               attrs={
                                                   'class': 'multiselect-dropdown form-control'}
                                           ))

    class Meta:
        model = Turma
        fields = ['turma']

class BookForm(forms.ModelForm):
    class Meta:
        model = Book
        fields = (
        'title', 'publication_date', 'author', 'price', 'pages', 'book_type',)


BookFormset = formset_factory(BookForm, extra=1)

class BookModelForm(BSModalModelForm):
    class Meta:
        model = Book
        fields = ['title', 'description']


class LoginForm(forms.Form):
    username = forms.CharField()
    password = forms.CharField(widget=forms.PasswordInput)


class UserEditForm(forms.ModelForm):
    class Meta:
        model = User
        fields = ('first_name', 'last_name', 'email')


class ProfileEditForm(forms.ModelForm):
    class Meta:
        model = Profile
        fields = ('date_of_birth', 'photo')


class UserRegistrationForm(forms.ModelForm):
    password = forms.CharField(label='Password',
                               widget=forms.PasswordInput)
    password2 = forms.CharField(label='Repeat password',
                                widget=forms.PasswordInput)

    class Meta:
        model = User
        fields = ('username', 'first_name', 'email')

    def clean_password2(self):
        cd = self.cleaned_data
        if cd['password'] != cd['password2']:
            raise forms.ValidationError('Passwords don\'t match.')
        return cd['password2']

account/views.py
# Create your views here.
from bootstrap_modal_forms.generic import BSModalCreateView, BSModalUpdateView
from django.contrib import messages
from django.contrib.auth import authenticate, login
from django.contrib.auth.decorators import login_required
from django.contrib.auth.models import User
from django.http import HttpResponse
from django.http import JsonResponse
from django.shortcuts import get_object_or_404
from django.shortcuts import render, redirect
from django.template.loader import render_to_string
from django.urls import reverse_lazy
from django.views.decorators.http import require_POST
from django.views.generic import CreateView

from actions.models import Action
from actions.utils import create_action
from common.decorators import ajax_required
from .forms import BookForm, BookFormset
from .forms import LoginForm, UserRegistrationForm, UserEditForm, \
    ProfileEditForm, BookModelForm, TurmaForm
from .models import Contact
from .models import Profile, Book


class CreateTurma(CreateView):
    form_class = TurmaForm
    template_name = 'account/create_turma.html'


def create_book_normal(request):
    template_name = 'account/create_normal.html'
    heading_message = 'Formset Demo'

    if request.method == 'GET':
        formset = BookFormset(request.GET or None)
    elif request.method == 'POST':
        formset = BookFormset(request.POST)
        print(formset.errors)
        if formset.is_valid():
            for form in formset:
                # extract name from each form and save
                name = form.cleaned_data.get('name')
                # save book instance
                if name:
                    Book(name=name).save()
            # once all books are saved, redirect to book list view
            return redirect('book_list')
    return render(request, template_name, {
        'formset': formset,
        'heading': heading_message,
    })


def create_book(request):
    books = Book.objects.all()
    response_data = {}
    print(request.POST)
    if request.POST.get('action') == 'post':
        title = request.POST.get('title')
        description = request.POST.get('description')

        response_data['title'] = title
        response_data['description'] = description

        Book.objects.create(
            title=title,
            description=description,
        )
        print(response_data)
        return JsonResponse(response_data)

    return render(request, 'account/index.html', {'books': books})


def book_list(request):
    books = Book.objects.all()

    return render(request, 'account/book_list.html', {'books': books})


def save_book_form(request, form, template_name):
    data = dict()

    if request.method == 'POST':
        form = BookForm(request.POST)

        if form.is_valid():
            form.save()
            data['form_is_valid'] = True

            books = Book.objects.all()
            data['html_book_list'] = render_to_string(
                'account/includes/partial_book_list.html', {
                    'books': books
                })
        else:
            data['form_is_valid'] = False

    context = {'form': form}
    data['html_form'] = render_to_string(template_name,
                                         context, request=request)
    return JsonResponse(data)


def book_create(request):
    if request.method == 'POST':
        form = BookForm(request.POST)
    else:
        form = BookForm()

    return save_book_form(request, form,
                          'account/includes/partial_book_create.html')


def book_update(request, pk):
    book = get_object_or_404(Book, pk=pk)

    if request.method == 'POST':
        form = BookForm(request.POST, instance=book)
    else:
        form = BookForm(instance=book)

    return save_book_form(request, form,
                          'account/includes/partial_book_update.html')


def books(request):
    data = dict()
    if request.method == 'GET':
        books = Book.objects.all()
        print(books)
        data['table'] = render_to_string('_book_table.html', {'books': books},
                                         request=request)

        return JsonResponse(data)


class BookCreateView(BSModalCreateView):
    template_name = 'account/create_book.html'
    form_class = BookModelForm
    success_message = 'Success: Book was created.'
    success_url = reverse_lazy('dashboard')


class BookUpdateView(BSModalUpdateView):
    model = Book
    template_name = 'account/update_book.html'
    form_class = BookModelForm
    success_message = 'Success: Book was updated.'
    success_url = reverse_lazy('index')


@ajax_required
@require_POST
@login_required
def user_follow(request):
    user_id = request.POST.get('id')
    action = request.POST.get('action')
    if user_id and action:
        try:
            user = User.objects.get(id=user_id)
            if action == 'follow':
                Contact.objects.get_or_create(
                    user_from=request.user,
                    user_to=user
                )
                create_action(request.user, 'is following', user)
            else:
                Contact.objects.filter(user_from=request.user,
                                       user_to=user).delete()
            return JsonResponse({'status': 'ok'})
        except User.DoesNotExist:
            return JsonResponse({'status': 'error'})
    return JsonResponse({'status': 'error'})


@login_required
def user_list(request):
    users = User.objects.filter(is_active=True)

    return render(request, 'account/user/list.html', {'section': 'people',
                                                      'users': users})


@login_required
def user_detail(request, username):
    user = get_object_or_404(User,
                             username=username,
                             is_active=True)

    return render(request, 'account/user/detail.html', {'section': 'people',
                                                        'user': user})


@login_required
def edit(request):
    if request.method == 'POST':
        user_form = UserEditForm(instance=request.user,
                                 data=request.POST)
        profile_form = ProfileEditForm(instance=request.user.profile,
                                       data=request.POST,
                                       files=request.FILES)
        if user_form.is_valid() and profile_form.is_valid():
            user_form.save()
            profile_form.save()
            messages.success(request, 'Profile updated successfuly')
        else:
            messages.error(request, 'Error updating your profile')

    else:
        user_form = UserEditForm(instance=request.user)
        profile_form = ProfileEditForm(
            instance=request.user.profile)
    return render(request,
                  'account/edit.html',
                  {'user_form': user_form,
                   'profile_form': profile_form})


def register(request):
    if request.method == 'POST':
        user_form = UserRegistrationForm(request.POST)
        if user_form.is_valid():
            # Create a new user obj but avoid savind it yet
            new_user = user_form.save(commit=False)
            new_user.set_password(
                user_form.cleaned_data['password']
            )
            # Save the user obj
            new_user.save()
            # Create the user profile
            Profile.objects.create(user=new_user)
            create_action(new_user, 'has created an account')
            return render(request,
                          'account/register_done.html',
                          {'new_user': new_user})
    else:
        user_form = UserRegistrationForm()
    return render(request,
                  'account/register.html',
                  {'user_form': user_form})


@login_required
def dashboard(request):
    # Display all actions by default
    actions = Action.objects.exclude(user=request.user)
    following_ids = request.user.following.value_list('id', flat=True)

    if following_ids:
        # If user is following other, retrieve only their actions
        actions = actions.filter(user_id__in=following_ids)
    actions = actions.select_related(
        'user', 'user__profile').prefetch_related('target')[:10]

    return render(request,
                  'account/dashboard.html',
                  {'section': 'dashboard',
                   'actions': actions})


def user_login(request):
    if request.method == 'POST':
        form = LoginForm(request.POST)
        if form.is_valid():
            cd = form.cleaned_data
            user = authenticate(request,
                                username=cd['username'],
                                password=cd['password'])
            if user is not None:
                if user.is_active:
                    login(request, user)
                    return HttpResponse('Authenticated successfully')
                else:
                    return HttpResponse('Disable Account')
            else:
                return HttpResponse('Login Inválido')
    else:
        form = LoginForm()
    return render(request, 'account/login.html', {'form': form})

account/templates/_book_table.html
<table id="books-table{{ i }}" class="table">
  <thead>
  <tr>
    <th class="text-center" scope="col">#</th>
    <th class="text-center" scope="col">Title</th>
    <th class="text-center" scope="col">Author</th>
    <th class="text-center" scope="col">Read / Update / Delete</th>
  </tr>
  </thead>
  <tbody>
  {% for book in books %}
    <tr>
      <th class="text-center" scope="row">{{ forloop.counter }}</th>
      <td class="text-center">{{ book.title }}</td>
      <td class="text-center">{{ book.description }}</td>
      <td class="text-center">
        <!-- Read book buttons -->
        <button type="button" class="bs-modal read-book btn btn-sm btn-primary" data-form-url="">
          <span class="fa fa-eye"></span>
        </button>
        <!-- Update book buttons -->
        <button type="button" class="update-book btn btn-sm btn-primary" title="Title" data-form-url="{% url 'update_book' book.pk %}">
          <span class="fa fa-check"></span>
        </button>
        <!-- Delete book buttons -->
        <button type="button" class="bs-modal delete-book btn btn-sm btn-danger" data-form-url="">
          <span class="fa fa-trash"></span>
        </button>
      </td>
    </tr>
  {% endfor %}
  </tbody>
</table>

account/templates/_modal.html
<div class="modal fade" id="create-modal" tabindex="-1" role="dialog"
     aria-hidden="true">
    <div class="modal-dialog mt-5">
        <div class="modal-content">
        </div>
    </div>
</div>

<div class="modal fade" tabindex="-1" role="dialog" id="modal">
    <div class="modal-dialog mt-5" role="document">
        <div class="modal-content"></div>
    </div>
</div>

account/templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>{% block title %}{% endblock %}</title>
    <link href="{% static "css/base.css" %}" rel="stylesheet">
    <link rel="stylesheet"
          href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css"
          integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm"
          crossorigin="anonymous">
    <link rel="stylesheet"
          href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.2/css/all.min.css"
          integrity="sha512-HK5fgLBL+xu6dm/Ii3z4xhlSUyZgTT9tuc/hSrtw6uzJOvgRr2a9jyxxT1ely+B+xFAmJKVSTbpM/CuL7qxO8w=="
          crossorigin="anonymous"/>
</head>
<body>
<div id="header">
    <span class="logo">Bookmarks</span>v
    {% if request.user.is_authenticated %}
        <ul class="menu">
            <li {% if section == "dashboard" %}class="selected"{% endif %}>
                <a href="{% url "dashboard" %}">My dashboard</a>
            </li>
            <li {% if section == "images" %}class="selected"{% endif %}>
                <a href="#">Images</a>
            </li>
            <li {% if section == "people" %}class="selected"{% endif %}><a
                    href="{% url "user_list" %}">People</a>
            </li>
            <li {% if section == "images" %}class="selected"{% endif %}><a
                    href="{% url "images:list" %}">Images</a>
            </li>
        </ul>
    {% endif %}

    <span class="user">
       {% if request.user.is_authenticated %}
           Hello {{ request.user.first_name }},
           <a href="{% url "logout" %}">Logout</a>
       {% else %}
           <a href="{% url "login" %}">Log-in</a>
       {% endif %}
</span>
</div>
{% if messages %}
    <ul class="messages">
        {% for message in messages %}
            <li class="{{ message.tags }}">
                {{ message|safe }}
                <a href="#" class="close">x</a>
            </li>
        {% endfor %}
    </ul>
{% endif %}
<div id="content">
    {% block content %}
    {% endblock %}
</div>
{#<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.4.1/#}
{#   jquery.min.js"></script>#}
{#<script src="https://cdn.jsdelivr.net/npm/js-cookie@2.2.1/src/ js.cookie.min.js"></script>#}

<script src="https://code.jquery.com/jquery-3.2.1.min.js"
        integrity="sha256-hwg4gsxgFZhOsEEamdOYGBf13FyQuiTwlAQgxVSNgt4="
        crossorigin="anonymous"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js"
        integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q"
        crossorigin="anonymous"></script>
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js"
        integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl"
        crossorigin="anonymous"></script>
<script src="{% static 'js/jquery.bootstrap.modal.forms.js' %}"></script>
{% block extrascripts %}{% endblock extrascripts %}

</body>
</html>